"""empty message

Revision ID: 0d07a3963ad6
Revises: 5f7e8fd5ac44
Create Date: 2021-06-04 21:13:56.083569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d07a3963ad6'
down_revision = '5f7e8fd5ac44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('line_new_users_line_userId_key', 'line_new_users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('line_new_users_line_userId_key', 'line_new_users', ['line_userId'])
    # ### end Alembic commands ###
