"""empty message

Revision ID: 0d63adb8c19d
Revises: c8655daf821f
Create Date: 2021-06-19 19:29:26.097578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d63adb8c19d'
down_revision = 'c8655daf821f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_item_epa',
    sa.Column('milestoneitem_id', sa.Integer(), nullable=False),
    sa.Column('epa_id', sa.Integer(), nullable=False),
    sa.Column('min_epa_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['epa_id'], ['epa.id'], ),
    sa.ForeignKeyConstraint(['milestoneitem_id'], ['milestone_item.id'], ),
    sa.PrimaryKeyConstraint('milestoneitem_id', 'epa_id')
    )
    op.drop_table('milestone_item_EPA')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_item_EPA',
    sa.Column('milestoneitem_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('epa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_epa_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['epa_id'], ['epa.id'], name='milestone_item_EPA_epa_id_fkey'),
    sa.ForeignKeyConstraint(['milestoneitem_id'], ['milestone_item.id'], name='milestone_item_EPA_milestoneitem_id_fkey'),
    sa.PrimaryKeyConstraint('milestoneitem_id', 'epa_id', name='milestone_item_EPA_pkey')
    )
    op.drop_table('milestone_item_epa')
    # ### end Alembic commands ###
