"""empty message

Revision ID: 2df6d9ae3e73
Revises: 0d07a3963ad6
Create Date: 2021-06-13 19:45:20.399675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df6d9ae3e73'
down_revision = '0d07a3963ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corecompetence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corecompetence_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=64), nullable=True),
    sa.Column('level_1_options', sa.String(length=1024), nullable=True),
    sa.Column('level_2_options', sa.String(length=1024), nullable=True),
    sa.Column('level_3_options', sa.String(length=1024), nullable=True),
    sa.Column('level_4_options', sa.String(length=1024), nullable=True),
    sa.Column('level_5_options', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['corecompetence_id'], ['corecompetence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('epa_milestone',
    sa.Column('epa_id', sa.Integer(), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['epa_id'], ['epa.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('epa_milestone')
    op.drop_table('milestone')
    op.drop_table('corecompetence')
    # ### end Alembic commands ###
