"""empty message

Revision ID: 2f040ba42a6f
Revises: cae401f028e1
Create Date: 2021-07-17 21:00:01.016460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f040ba42a6f'
down_revision = 'cae401f028e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reviewee_note', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'reviewee_note')
    # ### end Alembic commands ###
