"""empty message

Revision ID: 5d4883532749
Revises: 3623222ba458
Create Date: 2021-04-30 22:49:04.965480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4883532749'
down_revision = '3623222ba458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('implement_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'implement_date')
    # ### end Alembic commands ###
