"""empty message

Revision ID: 66aef658993e
Revises: 2f040ba42a6f
Create Date: 2021-07-17 21:21:38.385430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66aef658993e'
down_revision = '2f040ba42a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('can_make_review', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('can_be_review', sa.Boolean(), nullable=True))
    op.drop_column('role', 'can_delete_unfin_review')
    op.drop_column('role', 'can_edit_unfin_review')
    op.drop_column('role', 'can_create_review')
    op.drop_column('role', 'can_request_review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('can_request_review', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('role', sa.Column('can_create_review', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('role', sa.Column('can_edit_unfin_review', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('role', sa.Column('can_delete_unfin_review', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('role', 'can_be_review')
    op.drop_column('role', 'can_make_review')
    # ### end Alembic commands ###
