"""empty message

Revision ID: 88ea5cdc390b
Revises: a34c4754f81d
Create Date: 2021-05-03 23:44:38.306291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ea5cdc390b'
down_revision = 'a34c4754f81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('can_create_and_edit_review', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('can_request_review', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('is_manager', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'is_manager')
    op.drop_column('role', 'can_request_review')
    op.drop_column('role', 'can_create_and_edit_review')
    # ### end Alembic commands ###
