"""empty message

Revision ID: c3522b6acfcc
Revises: a8c797c06c46
Create Date: 2021-07-12 18:11:10.434175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3522b6acfcc'
down_revision = 'a8c797c06c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('status_draft', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('status_complete', sa.Boolean(), nullable=True))
    op.drop_column('reviews', 'complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'status_complete')
    op.drop_column('reviews', 'status_draft')
    # ### end Alembic commands ###
