"""empty message

Revision ID: c8655daf821f
Revises: ea25eaaf1bfa
Create Date: 2021-06-19 16:43:11.463818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8655daf821f'
down_revision = 'ea25eaaf1bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestone_item_EPA',
    sa.Column('milestoneitem_id', sa.Integer(), nullable=False),
    sa.Column('epa_id', sa.Integer(), nullable=False),
    sa.Column('min_epa_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['epa_id'], ['epa.id'], ),
    sa.ForeignKeyConstraint(['milestoneitem_id'], ['milestone_item.id'], ),
    sa.PrimaryKeyConstraint('milestoneitem_id', 'epa_id')
    )
    op.drop_table('epa_milestone')
    op.drop_column('milestone', 'level_4_options')
    op.drop_column('milestone', 'level_2_options')
    op.drop_column('milestone', 'level_3_options')
    op.drop_column('milestone', 'level_1_options')
    op.drop_column('milestone', 'level_5_options')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('level_5_options', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('milestone', sa.Column('level_1_options', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('milestone', sa.Column('level_3_options', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('milestone', sa.Column('level_2_options', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('milestone', sa.Column('level_4_options', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.create_table('epa_milestone',
    sa.Column('epa_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('milestone_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['epa_id'], ['epa.id'], name='epa_milestone_epa_id_fkey'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], name='epa_milestone_milestone_id_fkey')
    )
    op.drop_table('milestone_item_EPA')
    op.drop_table('milestone_item')
    # ### end Alembic commands ###
