"""empty message

Revision ID: d79136b26f8e
Revises: 5d4883532749
Create Date: 2021-05-01 13:29:07.564721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79136b26f8e'
down_revision = '5d4883532749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_externalgroup',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('user_group')
    op.add_column('users', sa.Column('interal_group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'groups', ['interal_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'interal_group_id')
    op.create_table('user_group',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='user_group_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_group_user_id_fkey')
    )
    op.drop_table('user_externalgroup')
    # ### end Alembic commands ###
