"""empty message

Revision ID: ea25eaaf1bfa
Revises: 181546e713eb
Create Date: 2021-06-14 23:27:00.536727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea25eaaf1bfa'
down_revision = '181546e713eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_activated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_activated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
